---
# tasks file for ansible-docker-role

- name: Install required packages
  apt: name={{ item }} update_cache=yes state=present force=yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - openssl
    - python3-pip
    - python3-dev

- name: get gpq key
  shell: curl -sSL https://get.docker.com/gpg | apt-key add -

- name: add repository
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: policy docker-ce
  shell: apt-cache policy docker-ce

- name: Install Docker
  apt: name={{ item }} update_cache=yes state=present force=yes
  with_items:
    - docker-ce

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.24.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755

- name: restart docker
  command: echo "this task will restart the docker services"
  notify: "restart docker"
